unipro/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.Home, name='home'),
    path('<int:category>', views.GetPostCategory, name='GetPostCategory'),
    path('news/', views.News, name='News'),
    path('news/loadMorePost', views.loadMorePost, name='NewsLoader'),
    path('news/<str:post_news>', views.detail_news, name='details'),

]

unipro/unipro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainApp.urls')),
    path('blog/', include('blog.urls')),
    path('Identification', include('Identification.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unipro/blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from slugify import slugify
from autoslug import AutoSlugField
from taggit.managers import TaggableManager


# Create your models here.


class Category(models.Model):
    name = models.CharField("نام", max_length=30)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'پیش نویس'),
        ('published', 'منتشر شده')
    )

    title = models.CharField("عنوان", max_length=250, unique=True)
    abstract = models.CharField("خلاصه", max_length=100)
    slug = AutoSlugField(populate_from='title', allow_unicode=True)
    author = models.ForeignKey(User, related_name="Author_Post", on_delete=models.CASCADE)
    body = models.TextField("متن")
    defaultImage = models.ImageField("عکس پیش فرض", upload_to="img/News", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = TaggableManager()
    created = models.DateTimeField("تاریخ انتشار", auto_now_add=True)
    updated = models.DateTimeField("تاریخ ویرایش", auto_now_add=True)
    status = models.CharField("وضعیت", max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:details', args=[self.slug])


class PhotoPost(models.Model):
    name = models.CharField("نام", max_length=200)
    address = models.ImageField(upload_to='img/post/')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField("متن", )
    email = models.EmailField("ایمیل", )
    created = models.DateTimeField("تاریخ ایجاد", )
    published = models.BooleanField("وضعیت انتشار", default=False)

unipro/templates/News.html
{% extends "Layouts/Normal/base.html" %}
{% load static %}
{% load mathfilters %}

{% block css %}
<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="" style="">
    <div class="d-flex" style="direction:RTL; text-align: right;margin-top: 30px">
        <div class="container" id="new">
          <span class="list-group-item text-center" style="margin-bottom: 5px"><b>اخبار</b></span>
          <div class="list-group-item text-center">
            <div class="container">
              <form class="form-horizontal" method="get" action="{% url 'blog:News' %}">
                <div class="row">
                        <div class="col-md-5">
                            <label >جستو و جو</label>
                            <input class="form-control border" type="text" name="text" value="{{ text }}" placeholder="چیز برای جست و جو بنویسید">
                        </div>
                        <div class="col-md-4" >
                            <div class="form-group">
                                <label>معمولی</label><br>
                                <select class="col-md-8" id="example" name="state">
                                    <option value="0" >همه زیر دسته ها</option>
                                  {% for category in categories %}
                                      {% if state == category.id%}
                                          <option selected value="{{ category.id}}">{{ category.name }}</option>
                                      {% else %}
                                          <option value="{{ category.id}}">{{ category.name }}</option>
                                      {% endif %}
                                  {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3" style="margin-top: 25px">
                        <input class="btn btn-primary  " type="submit" value="جست و جو">
                      </div>
                </div>
              </form>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="container " style="text-align: center">
              <div class="row" style="text-align: right">
                    {% for post in posts %}
                  {% if forloop.first %}
                      <div class="col-md-4" id="col-name-{{ forloop.counter0 }}">
                  {% endif %}
                  {% with forloop.counter0|mod:3  as i %}
                  {% if forloop.counter0 > 0 and i == 0   %}
                    </div>
                    <div class="col-md-4" id="col-name-{{ forloop.counter0 }}">
                  {% endif %}
                  {% endwith %}
                    <div class=" align-self-start" style="margin-bottom: 10px">
                    <div class="card mb card-columns">
                      <img class="card-img-top" src="{{ post.defaultImage.url }}" alt="Card image cap">
                      <div class="card-body mb">
                        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                        <p class="card-text">{{ post.abstract }}</p>
                          <p>{{ post.created }}</p>
                      </div>
                        <div class="card-footer mb">
                            دسته بندی : {{ post.category }}
                        </div>
                    </div>
                  </div>
                  {% if forloop.last %}
                      </div>
                  {% endif %}
                {% endfor %}
              </div>
              <!-- pagination -->
              <a id="loadMorePost"  class="btn btn-info col-md-3">بیشتر</a>
            </div>
          </div>
        </div>
    </div>
    <hr>
      <div class="text-center" style="margin-top: 20px">
        <img src="{% static 'img/طراحی-بنر-نت-برگ.gif' %}"  alt="logo fdrestion">
        <br><br>
      </div>
  </div>
{% endblock %}

{% block script %}
<script src="{% static 'js/select2.min.js' %}"></script>
    <script>
    $(function() {
        $("#example").select2();
        });
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $('#loadMorePost').click(function () {
        $.ajax({
            type:"GET",
            url: "{% url 'blog:NewsLoader' %}?text={{ text }}&page={{ page }}&state={{ state }}",
            success: function (data) {
                $.each(data,function (index,item) {
                    if (index % 3 == 0){
                        $("#col-name-0").append(

                        );
                    }else if (index % 3 == 1){
                        $("#col-name-3").append( "<h1>" + item['title']+ "</h1>");
                    }else {
                        $("#col-name-6").append( "<h1>" + item['title']+ "</h1>");
                    }
                })
            }
        });
    });

    </script>

{% endblock %}

unipro/templates/Roll.html
{% extends 'Layouts/Normal/base.html' %}
{% load static %}

{% block content %}
    <div class="d-flex" style="direction:RTL; text-align: right;margin-top: 30px">
            <div class="col-sm-12"  id="new">
                <div class="container">
                    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                       {% for category in allcategory %}
                            <li class="nav-item">
                                {% if forloop.first %}
                                    <a class="nav-link active" id="pills-{{category.id}}-tab" data-toggle="pill" href="#pills-{{category.id}}" role="tab" aria-controls="pills-{{category.id}}" aria-selected="true">{{category.name}}</a>
                                {% else %}
                                    <a class="nav-link " id="pills-{{category.id}}-tab" data-toggle="pill" href="#pills-{{category.id}}" role="tab" aria-controls="pills-{{category.id}}" aria-selected="true">{{category.name}}</a>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="tab-content white" id="pills-tabContent">
                        {% for category in allcategory %}
                            {% if forloop.first %}
                                <div class="tab-pane fade show active" id="pills-{{category.id}}" role="tabpanel" aria-labelledby="pills-{{category.id}}-tab">
                                    <div class="row" style="padding: 20px">
                                        <div class="nav flex-column nav-pills col-md-2" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                            {% for post in allpost %}
                                                {% if post.categoryguid.id == category.id %}
                                                    {% if forloop.first %}
                                                        <a class="nav-link active" id="v-pills-{{ post.id }}-tab" data-toggle="pill" href="#v-pills-{{ post.id }}" role="tab" aria-controls="v-pills-{{ post.id }}" aria-selected="true">{{ post.name }}</a>
                                                        {% else %}
                                                        <a class="nav-link" id="v-pills-{{ post.id }}-tab" data-toggle="pill" href="#v-pills-{{ post.id }}" role="tab" aria-controls="v-pills-{{ post.id }}" aria-selected="false">{{ post.name }}</a>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="tab-content col-md-9" id="v-pills-tabContent">
                                            {% for post in allpost %}
                                                {% if post.categoryguid.id == category.id %}
                                                    {% if forloop.first %}
                                                        <div class="tab-pane fade show active" id="v-pills-{{ post.id }}" role="tabpanel" aria-labelledby="v-pills-{{ post.id }}-tab">
                                                            {% include "Layouts/Normal/RollPost.html" with post=post %}
                                                        </div>
                                                        {% else %}
                                                        <div class="tab-pane fade" id="v-pills-{{ post.id }}" role="tabpanel" aria-labelledby="v-pills-{{ post.id }}-tab">
                                                            {% include "Layouts/Normal/RollPost.html" with post=post %}
                                                        </div>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                         </div>
                                    </div>
                                </div>
                            {% else %}
                                <div class="tab-pane fade" id="pills-{{category.id}}" role="tabpanel" aria-labelledby="pills-{{category.id}}-tab">
                                    <div class="row" style="padding: 20px">
                                        <div class="nav flex-column nav-pills col-md-2" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                            {% for post in allpost %}
                                                {% if post.categoryguid_id == category.id %}
                                                    {% if forloop.first %}
                                                        <a class="nav-link active" id="v-pills-{{ post.id }}-tab" data-toggle="pill" href="#v-pills-{{ post.id }}" role="tab" aria-controls="v-pills-{{ post.id }}" aria-selected="true">{{ post.name }}</a>
                                                        {% else %}
                                                        <a class="nav-link" id="v-pills-{{ post.id }}-tab" data-toggle="pill" href="#v-pills-{{ post.id }}" role="tab" aria-controls="v-pills-{{ post.id }}" aria-selected="false">{{ post.name }}</a>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="tab-content col-md-9" id="v-pills-tabContent">
                                            {% for post in allpost %}
                                                {% if post.categoryguid.id == category.id %}
                                                    {% if forloop.first %}
                                                        <div class="tab-pane fade show active" id="v-pills-{{ post.id }}" role="tabpanel" aria-labelledby="v-pills-{{ post.id }}-tab">
                                                            {% include "Layouts/Normal/RollPost.html" with post=post %}
                                                        </div>
                                                        {% else %}
                                                        <div class="tab-pane fade" id="v-pills-{{ post.id }}" role="tabpanel" aria-labelledby="v-pills-{{ post.id }}-tab">
                                                            {% include "Layouts/Normal/RollPost.html" with post=post %}
                                                        </div>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
    </div>
    <br>
{% endblock %}

unipro/templates/aboutUs.html
{% extends "Layouts/Normal/base.html" %}
{% load static %}

{% block content %}
<div class="d-flex" style="direction:RTL; text-align: right;margin-top: 30px">
            <div class="col-sm-12"  id="new">
                <div class="container">
                    <span class="list-group-item " style="margin-bottom: 15px"><h4><b>فدراسیون اتوموبیل رانی و موتور سواری قزوین</b></h4>
                    <h6><b>هیئت اتوموبیل رانی و موتور سواری استان قزونی در تاریخ 1379 شکل گرفت و ساختمان اصلی آن در میدان ... واقع است.</b></h6>
                    </span>

                    <div class="card-deck">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3">
                                        <img class="card-img-top" src="{% static 'img/user.png' %}" alt="Card image cap5">
                                    </div>
                                    <div class="col-md-9">
                                        <h5 class="card-title">مهدی عزپور</h5>
                                        <p class="card-text">سمت : رئیس هیئت</p>
                                        <p class="card-text">تاریخ شروع به خدمت : 1398/7/21</p>
                                        <p class="card-text">ایمیل : ezpour.me@gmail.com</p>
                                        <p class="card-text">شماره تماس : 09107604663</p>                                    </div>
                                </div>
                                </div>
                            <div class="card-footer">
                                <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3">
                                        <img class="card-img-top" src="{% static 'img/user.png' %}" alt="Card image cap5">
                                    </div>
                                    <div class="col-md-9">
                                        <h5 class="card-title">محمد حسین حاج کاظم نیلی</h5>
                                        <p class="card-text">سمت : رئیس هیئت</p>
                                        <p class="card-text">تاریخ شروع به خدمت : 1398/7/21</p>
                                        <p class="card-text">ایمیل : ezpour.me@gmail.com</p>
                                        <p class="card-text">شماره تماس : 09107604663</p>                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="card-deck">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3">
                                        <img class="card-img-top" src="{% static 'img/user.png' %}" alt="Card image cap5">
                                    </div>
                                    <div class="col-md-9">
                                        <h5 class="card-title">محمد امین جمالی</h5>
                                        <p class="card-text">سمت : رئیس هیئت</p>
                                        <p class="card-text">تاریخ شروع به خدمت : 1398/7/21</p>
                                        <p class="card-text">ایمیل : ezpour.me@gmail.com</p>
                                        <p class="card-text">شماره تماس : 09107604663</p>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-3">
                                        <img class="card-img-top" src="{% static 'img/user.png' %}" alt="Card image cap5">
                                    </div>
                                    <div class="col-md-9">
                                        <h5 class="card-title">علی اکبر فاظلی</h5>
                                        <p class="card-text">سمت : رئیس هیئت</p>
                                        <p class="card-text">تاریخ شروع به خدمت : 1398/7/21</p>
                                        <p class="card-text">ایمیل : ezpour.me@gmail.com</p>
                                        <p class="card-text">شماره تماس : 09107604663</p>                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Last updated 3 mins ago</small>
                            </div>
                        </div>
                    </div>
                    <br>
                </div>
                </div>
            </div>

        </div>
{% endblock %}

unipro/templates/contactUs.html
{% extends "Layouts/Normal/base.html" %}
{% load static %}

{% block content %}
    <div class="d-flex" style="margin-top: 30px">
        <div class="col-sm-12 col-md-9 ">
             <div class="container">
                <span class="list-group-item text-center" style="margin-bottom: 5px"><b>اخبار</b></span>
             </div>
        </div>
        <div class="col-sm-12 col-md-3 text-center">
            {% include "Layouts/Normal/sidbarLeft1.html" %}
        </div>
    </div>
    <hr>
      <div class="text-center" style="margin-top: 20px">
        <img src="{% static 'img/طراحی-بنر-نت-برگ.gif' %}"  alt="logo fdrestion">
      </div>
        <br><br>
      </div>{% endblock %}

unipro/templates/detail-news.html
{% extends "Layouts/Normal/base.html" %}
{% load static %}

{% block content %}

    <div class="d-flex" style="direction:RTL; text-align: right;margin-top: 30px">
            <div class="col-sm-12 col-md-9 "  id="new">
                <div class="container">
                    <span class="list-group-item text-center" style="margin-bottom: 5px"><b>{{ post.title }}</b></span>
                    {% include "Layouts/Normal/slider.html" %}
                    <div class="row">
                        <div class="container ">
                            <div class="row">
                                <div class="container">
                                    <div class="well">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="">

                                                    <hr>
                                                    <pre class="text-justify">
                                                        <h3>مشروح خبر :</h3><br>{{ post.body }}
                                                    </pre>
                                                    <hr>
                                                    <small>{{ post.created }}</small><br>
                                                    <hr>
                                                    دسته بندی ها : {{ post.category }}
                                                    <hr>
                                                    <form method="post" action="#">
                                                        {% csrf_token %}
                                                        <div class="form-group shadow-textarea">
                                                            <label for="exampleFormControlTextarea6">نظر خود را با ما به اشتراک بگذارید</label>
                                                            <textarea class="form-control z-depth-1" id="exampleFormControlTextarea6" rows="3" placeholder="چیزی بنویسید برای ما ..."></textarea>
                                                        </div>
                                                        <input type="submit" class="btn btn-info" value="اضافه کردن">
                                                    </form>
                                                    <div class='container'>
                                                        <div class=" card comment-box">
                                                            {% if post.comment_set.all %}
                                                                {% for comment in post.comment_set.all %}
                                                                    <div class="card-body">
                                                                        <h5 class="card-header">{{ comment.email }}</h5>
                                                                        <p style="border: 2px solid rgba(214,214,214,1.00);padding: 5px">{{ comment.body }}</p>
                                                                    </div>
                                                                {% endfor %}
                                                            {% else %}
                                                                <h4>هنوز نظری ثبت نشده است</h4>
                                                            {% endif %}

                                                        </div>

                                                    </div>


                                                    <br>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include "Layouts/Normal/sidbarLeft1.html" %}

    </div>

{% endblock %}

unipro/templates/index.html
{% extends 'Layouts/Normal/base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}
<div class="" style="">
    {% include "Layouts/Normal/slider.html" %}
    <div class="d-flex" style="margin-top: 30px">
      <div class="col-sm-12 col-md-9 "  id="new">
        <div class="container" style="text-align: center" >
          <span class="list-group-item text-center" style="margin-bottom: 5px"><b>اخبار</b></span>
          <div class="row">
            <div class="container" >
              <div class="row" style="text-align: right">
              {% for post in posts %}
                  {% if forloop.first %}
                      <div class="col-md-4">
                  {% endif %}
                  {% with forloop.counter0|mod:3  as i %}
                  {% if forloop.counter0 > 0 and i == 0   %}
                    </div>
                    <div class="col-md-4" >
                  {% endif %}
                  {% endwith %}
                    <div class=" align-self-start" style="margin-bottom: 10px">
                    <div class="card mb card-columns">
                      <img class="card-img-top" src="{{ post.defaultImage.url }}" alt="Card image cap">
                      <div class="card-body mb">
                        <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                        <p class="card-text">{{ post.abstract }}</p>
                          <p>{{ post.created }}</p>
                      </div>
                        <div class="card-footer mb">
                            دسته بندی : {{ post.category }}
                        </div>
                    </div>
                  </div>
                  {% if forloop.last %}
                      </div>
                  {% endif %}
              {% endfor %}
              </div>
              <a href="{% url 'blog:News' %}" class="btn btn-info col-md-3">بیشتر</a>
            </div>

          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-3 text-center" id="importNews">
        {% include "Layouts/Normal/sidbarLeft1.html" %}
      </div>
    </div>
    <hr>
      <div class="text-center" style="margin-top: 20px">
        <img src="{% static 'img/طراحی-بنر-نت-برگ.gif' %}"  alt="logo fdrestion">
        <br><br>
      </div>
      <div class="text-center" >
        <span>همکاران</span>
        <br>
        <br>
        <div class="text-center ">

          <img style="width: 80px; height: 80px;margin-left: 20px" src="{% static 'img/logo/Rahvar-logo-LimooGraphic.png' %}"  alt="logo fdrestion">
          <img style="width: 80px; height: 80px;margin-left: 20px" src="{% static 'img/logo/لوگوی شهرداری.png' %}"  alt="logo fdrestion">
          <img style="width: 80px; height: 80px;margin-left: 20px" src="{% static 'img/logo/کاربرد-پیامک-در-هلال-احمر.png' %}"  alt="logo fdrestion">
          <img style="width: 80px; height: 80px;margin-left: 20px" src="{% static 'img/logo/11111111-256x300.png' %}"  alt="logo fdrestion">
        </div>
        <br>
      </div>
  </div>

{% endblock %}